export const VALUE_OF_KEYS = {
    /* -------- first row (highest) -------- */
    Backquote: {
      eng: '`',
      engH: '~',
      rus: 'ё',
      rusH: 'Ё',
    },
    Digit1: {
      eng: '1',
      engH: '!',
      rus: '1',
      rusH: '!',
    },
    Digit2: {
      eng: '2',
      engH: '@',
      rus: '2',
      rusH: '"',
    },
    Digit3: {
      eng: '3',
      engH: '#',
      rus: '3',
      rusH: '#',
    },
    Digit4: {
      eng: '4',
      engH: '$',
      rus: '4',
      rusH: ';',
    },
    Digit5: {
      eng: '5',
      engH: '%',
      rus: '5',
      rusH: '%',
    },
    Digit6: {
      eng: '6',
      engH: '^',
      rus: '6',
      rusH: ':',
    },
    Digit7: {
      eng: '7',
      engH: '&',
      rus: '7',
      rusH: '?',
    },
    Digit8: {
      eng: '8',
      engH: '*',
      rus: '8',
      rusH: '*',
    },
    Digit9: {
      eng: '9',
      engH: '(',
      rus: '9',
      rusH: '(',
    },
    Digit0: {
      eng: '0',
      engH: ')',
      rus: '0',
      rusH: ')',
    },
    Minus: {
      eng: '-',
      engH: '_',
      rus: '-',
      rusH: '_',
    },
    Equal: {
      eng: '=',
      engH: '+',
      rus: '=',
      rusH: '+',
    },
    Backspace: {
      eng: '← Backspace',
      engH: '← Backspace',
      rus: '← Backspace',
      rusH: '← Backspace',
    },
    /* -------- second row (tab qwerty) -------- */
    Tab: {
      eng: 'Tab ⇄',
      engH: 'Tab ⇄',
      rus: 'Tab ⇄',
      rusH: 'Tab ⇄',
    },
    KeyQ: {
      eng: 'q',
      engH: 'Q',
      rus: 'й',
      rusH: 'Й',
    },
    KeyW: {
      eng: 'w',
      engH: 'W',
      rus: 'ц',
      rusH: 'Ц',
    },
    KeyE: {
      eng: 'e',
      engH: 'E',
      rus: 'у',
      rusH: 'У',
    },
    KeyR: {
      eng: 'r',
      engH: 'R',
      rus: 'к',
      rusH: 'К',
    },
    KeyT: {
      eng: 't',
      engH: 'T',
      rus: 'е',
      rusH: 'Е',
    },
    KeyY: {
      eng: 'y',
      engH: 'Y',
      rus: 'н',
      rusH: 'Н',
    },
    KeyU: {
      eng: 'u',
      engH: 'U',
      rus: 'г',
      rusH: 'Г',
    },
    KeyI: {
      eng: 'i',
      engH: 'I',
      rus: 'ш',
      rusH: 'Ш',
    },
    KeyO: {
      eng: 'o',
      engH: 'O',
      rus: 'щ',
      rusH: 'Щ',
    },
    KeyP: {
      eng: 'p',
      engH: 'P',
      rus: 'з',
      rusH: 'З',
    },
    BracketLeft: {
      eng: '[',
      engH: '{',
      rus: 'х',
      rusH: 'Х',
    },
    BracketRight: {
      eng: ']',
      engH: '}',
      rus: 'ъ',
      rusH: 'Ъ',
    },
    Backslash: {
      eng: '\\',
      engH: '|',
      rus: '\\',
      rusH: '/',
    },
    Delete: {
      eng: 'Delete',
      engH: 'Delete',
      rus: 'Delete',
      rusH: 'Delete',
    },
    /* -------- third row (Caps asdfgh) -------- */
    CapsLock: {
      eng: 'Caps Lock',
      engH: 'Caps Lock',
      rus: 'Caps Lock',
      rusH: 'Caps Lock',
    },
    KeyA: {
      eng: 'a',
      engH: 'A',
      rus: 'ф',
      rusH: 'Ф',
    },
    KeyS: {
      eng: 's',
      engH: 'S',
      rus: 'ы',
      rusH: 'Ы',
    },
    KeyD: {
      eng: 'd',
      engH: 'D',
      rus: 'в',
      rusH: 'В',
    },
    KeyF: {
      eng: 'f',
      engH: 'F',
      rus: 'а',
      rusH: 'А',
    },
    KeyG: {
      eng: 'g',
      engH: 'G',
      rus: 'п',
      rusH: 'П',
    },
    KeyH: {
      eng: 'h',
      engH: 'H',
      rus: 'р',
      rusH: 'Р',
    },
    KeyJ: {
      eng: 'j',
      engH: 'J',
      rus: 'о',
      rusH: 'О',
    },
    KeyK: {
      eng: 'k',
      engH: 'K',
      rus: 'л',
      rusH: 'Л',
    },
    KeyL: {
      eng: 'l',
      engH: 'L',
      rus: 'д',
      rusH: 'Д',
    },
    Semicolon: {
      eng: ';',
      engH: ':',
      rus: 'ж',
      rusH: 'Ж',
    },
    Quote: {
      eng: '\'',
      engH: '"',
      rus: 'э',
      rusH: 'Э',
    },
    Enter: {
      eng: 'Enter ↵',
      engH: 'Enter ↵',
      rus: 'Enter ↵',
      rusH: 'Enter ↵',
    },
    /* -------- fourth row (l-shift zxcvbn) -------- */
    ShiftLeft: {
      eng: '⇑ Shift',
      engH: '⇑ Shift',
      rus: '⇑ Shift',
      rusH: '⇑ Shift',
    },
    KeyZ: {
      eng: 'z',
      engH: 'Z',
      rus: 'я',
      rusH: 'Я',
    },
    KeyX: {
      eng: 'x',
      engH: 'X',
      rus: 'ч',
      rusH: 'Ч',
    },
    KeyC: {
      eng: 'c',
      engH: 'C',
      rus: 'с',
      rusH: 'С',
    },
    KeyV: {
      eng: 'v',
      engH: 'V',
      rus: 'м',
      rusH: 'М',
    },
    KeyB: {
      eng: 'b',
      engH: 'B',
      rus: 'и',
      rusH: 'И',
    },
    KeyN: {
      eng: 'n',
      engH: 'N',
      rus: 'т',
      rusH: 'Т',
    },
    KeyM: {
      eng: 'm',
      engH: 'M',
      rus: 'ь',
      rusH: 'Ь',
    },
    Comma: {
      eng: ',',
      engH: '<',
      rus: 'б',
      rusH: 'Б',
    },
    Period: {
      eng: '.',
      engH: '>',
      rus: 'ю',
      rusH: 'Ю',
    },
    Slash: {
      eng: '/',
      engH: '?',
      rus: '.',
      rusH: ',',
    },
    ArrowUp: {
      eng: 'ᐃ',
      engH: 'ᐃ',
      rus: 'ᐃ',
      rusH: 'ᐃ',
    },
    ShiftRight: {
      eng: '⇑ Shift',
      engH: '⇑ Shift',
      rus: '⇑ Shift',
      rusH: '⇑ Shift',
    },
    /* -------- fifth row (bottom row) -------- */
    ControlLeft: {
      eng: 'Ctrl',
      engH: 'Ctrl',
      rus: 'Ctrl',
      rusH: 'Ctrl',
    },
    MetaLeft: {
      eng: 'Win',
      engH: 'Win',
      rus: 'Win',
      rusH: 'Win',
    },
    AltLeft: {
      eng: 'Alt',
      engH: 'Alt',
      rus: 'Alt',
      rusH: 'Alt',
    },
    Space: {
      eng: '',
      engH: '',
      rus: '',
      rusH: '',
    },
    AltRight: {
      eng: 'Alt',
      engH: 'Alt',
      rus: 'Alt',
      rusH: 'Alt',
    },
    MetaRight: {
      eng: 'Win',
      engH: 'Win',
      rus: 'Win',
      rusH: 'Win',
    },
    ControlRight: {
      eng: 'Ctrl',
      engH: 'Ctrl',
      rus: 'Ctrl',
      rusH: 'Ctrl',
    },
    ArrowLeft: {
      eng: 'ᐊ',
      engH: 'ᐊ',
      rus: 'ᐊ',
      rusH: 'ᐊ',
    },
    ArrowDown: {
      eng: 'ᐁ',
      engH: 'ᐁ',
      rus: 'ᐁ',
      rusH: 'ᐁ',
    },
    ArrowRight: {
      eng: 'ᐅ',
      engH: 'ᐅ',
      rus: 'ᐅ',
      rusH: 'ᐅ',
    },
    Clear: {
      eng: 'Clear',
      engH: 'Clear',
      rus: 'Clear',
      rusH: 'Clear',
    },
  };
  
  export default VALUE_OF_KEYS;
  